sonar.projectKey=2024.ad-project.adria.22.client
sonar.projectName=2024.ad-project.adria.22.client
sonar.token=sqa_f4ebb6d2fe2c459ed86c0c115268d7bddbb9de21
sonar.host.url=https://sonarqube.ti.howest.be/
sonar.sources=src
sonar.coverage.exclusions=src/assets/css/reset.css
